# @package _global_

defaults:
  - override /experiment: debug
  - override /simulator: debug
  - override /model: debug
  - override /trainer: debug
  - override /artifacts: all
  - override /diagnostics: latent_embeddings
  - override /swanlab: debug

command: experiment
