# @package _global_

defaults:
  - override /experiment: formal_5x
  - override /simulator: debug
  - override /model: formal_5x
  - override /trainer: formal_5x
  - override /artifacts: all
  - override /diagnostics: disabled
  - override /swanlab: formal_5x

command: experiment
