# @package _global_

defaults:
  - override /experiment: optim
  - override /simulator: debug
  - override /model: debug
  - override /trainer: debug
  - override /artifacts: none
  - override /diagnostics: disabled
  - override /swanlab: optim
  - override /optim: formal

command: optim
