# @package _global_

defaults:
  - override /experiment: quick
  - override /simulator: quick
  - override /model: quick
  - override /trainer: quick
  - override /artifacts: quick
  - override /diagnostics: disabled
  - override /swanlab: quick

command: experiment
