defaults:
  - _self_
  - simulation: quick
  - training: small
  - baseline: default
  - optim: default
  - summary: default

command: simulate

paths:
  data_root: null
  data: null
  test_data: null
  train_root: null
  save_name: ${command}

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${paths.save_name}-${now:%Y%m%d-%H%M%S-%f}
  sweep:
    dir: multirun/${paths.save_name}-${now:%Y%m%d-%H%M%S-%f}
    subdir: ${hydra.job.num}
