# @package _global_
defaults:
  - _self_
  - /training: small
  - /optim: default

paths:
  root: outputs/optim
  prefix: ${name}-optim_${optim.name}
  suffix: ${now:%Y%m%d-%H%M%S-%f}
  dir: ${paths.root}/${paths.prefix}-${paths.suffix}
  data_root: data/simulated
  explicit_split:
    enabled: false
    train_data: data/simulated/train.pt
    test_data: data/simulated/test.pt

hydra:
  job:
    chdir: false
  run:
    dir: ${paths.dir}
  sweep:
    dir: outputs/multirun/optim/${now:%Y%m%d-%H%M%S-%f}
    subdir: ${hydra.job.num}
