# @package _global_
defaults:
  - _self_

train_roots: []
baseline_roots: []
train_labels: []
baseline_labels: []
metrics: [acc, ari, nmi, cindex]

paths:
  root: outputs/summary
  prefix: summary
  suffix: ${now:%Y%m%d-%H%M%S-%f}
  dir: ${paths.root}/${paths.prefix}-${paths.suffix}

hydra:
  job:
    chdir: false
  run:
    dir: ${paths.dir}
  sweep:
    dir: outputs/multirun/summary/${now:%Y%m%d-%H%M%S-%f}
    subdir: ${hydra.job.num}
